### ISSUE TITLE
[Bug] Full refresh not deleting materialized view with cascade

### ISSUE THREAD

**Issue by Dnirmania** [dbt-labs/dbt-redshift#740] opened 2024-03-26 17:50 UTC
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If execute `dbt run --models mv1 --full-refresh`, dbt try to drop mv with `drop materialized view if exists "database"."schema"."mv1";` command

### Expected Behavior

If execute `dbt run --models mv1 --full-refresh`, dbt try to drop mv with `drop materialized view if exists "database"."schema"."mv1" cascade;` command

### Steps To Reproduce

1.  Create mv1 materialized view.
2.  Create mv2 materialized view on top of mv1.
3.  Execute `dbt run --models mv1 --full-refresh.

### Environment

```markdown
- OS: ubuntu
- Python: 3.10
- dbt-core:  1.7.1
- dbt-redshift:  1.7.1
```

**Comment by dataders** [comment] 2024-03-29 15:15
Closing as I believe this is a dupe of #642. Please correct me if I'm wrong!

**Closed by dataders** 2024-03-29 15:15 UTC
Labels: bug, triage, materialized_views
