### ISSUE TITLE
[ADAP-564] [Regression] unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)

### ISSUE THREAD

**Issue by pdebelak** [dbt-labs/dbt-redshift#456] opened 2023-05-18 16:27 UTC
### Is this a regression in a recent version of dbt-redshift?

- [X] I believe this is a regression in dbt-redshift functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Some models sometimes give an error `unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)` that is potentially related to whatever the issue is in https://github.com/aws/amazon-redshift-python-driver/issues/142

### Expected/Previous Behavior

Models run correctly.

### Steps To Reproduce

1. Use `redshift-connector` instead of `psycopg2` to connect to redshift

### Relevant log output

```shell
16:19:06  Runtime Error in model my_model (models/my_model.sql)
16:19:06    unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)
```

### Environment

```markdown
- OS: debian 11.7
- Python: 3.8.16
- dbt-core (working version): 1.4.5
- dbt-redshift (working version): 1.4.0
- dbt-core (regression version): 1.5.0
- dbt-redshift (regression version): 1.5.1
```

**Comment by dbeatty10** [comment] 2023-05-19 15:57
@pdebelak thank you for reaching out!

And thanks for linking to https://github.com/aws/amazon-redshift-python-driver/issues/142

Is there a specific dbt project setup (model, seed, etc) that I can use to reproduce this error? Or is it really dependent upon something on the Redshift side of things that will be hard to reproduce?

My gut says that this is a `redshift_connector` issue that we won't be able to do much about rather than a dbt-redshift issue that we can fix -- any additional info you can give will be helpful to determine one from the other.

**Comment by pdebelak** [comment] 2023-05-19 16:03
@dbeatty10 I haven't figured out a reproducible example for this, but I agree that this seems to be an issue with `redshift-connector`. I opened the issue here because this is another one of the breaking changes caused by the switch from `psycopg2` to `redshift-connector` and I think the solution is to either just revert #251 or at least make the driver configurable. I opened [a discussion about this yesterday as well](https://github.com/dbt-labs/dbt-redshift/discussions/457) since it's a big change and would be breaking (much in the change to switch from `psycopg2` to `redshift-connector` was a large, breaking change).

**Comment by dbeatty10** [comment] 2023-05-19 21:28
@pdebelak Would you be willing to run the following and share the output?
```
dbt --log-format json run ...
```

Thank you for opening that Discussion -- I'll respond there.

**Comment by dbeatty10** [comment] 2023-05-31 14:02
### Root cause

When a network connection is lost unexpectedly, the error message doesn't help the user realize it's really a network connection issue.

### Background

Prior to Mar 27, 2021, the README of `pg8000` (predecessor to `redshift_connector`) [said](https://github.com/tlocke/pg8000/blob/c471e4dc64a631395960cfaad02983132bfa9b5a/README.adoc?plain=1#L1014-L1018):

> Occasionally, the network connection between pg8000 and the server may go
>   down. If pg8000 encounters a problem writing to a socket it raises
>   `BrokenPipeError: [Errno 32] Broken pipe`. If pg8000 encounters a problem
>   reading from a socket it raises `struct.error: unpack_from requires a buffer
>   of at least 5 bytes`.

### Potential solution

The solution is likely two parts:
1. Within redshift_connector, Raise a better Exception
2. Within dbt-redshift, handle that Exception as desired

These commits in `pg8000` could be used as inspiration for how to catch this error within redshift_connector and re-raise it as a network error instead:
- https://github.com/tlocke/pg8000/commit/4b0a6c6734fd8483e9f15db4c5eac38937370a36
- https://github.com/tlocke/pg8000/commit/b167253ad9c133416d6b4a7b3fac96558d396c0b

### Related issues

Here's a listing of related issues across both redshift_connector and pg8000:

#### pg8000
  - https://github.com/tlocke/pg8000/issues/65
  - https://github.com/tlocke/pg8000/issues/98
  - https://github.com/tlocke/pg8000/issues/102

#### redshift_connector
  - https://github.com/aws/amazon-redshift-python-driver/issues/16
  - https://github.com/aws/amazon-redshift-python-driver/issues/96
  - https://github.com/aws/amazon-redshift-python-driver/issues/124
  - https://github.com/aws/amazon-redshift-python-driver/issues/142

**Comment by dataders** [comment] 2023-06-06 14:47
closing in favor of: https://github.com/aws/amazon-redshift-python-driver/issues/164

@pdebelak I have confidence that we can get this fixed on the driver once and for all! thanks again for all your work reporting this

**Closed by dataders** 2023-06-06 14:47 UTC
Labels: bug, regression, redshift_connector

**Comment by nischay-merkle** [comment] 2023-07-05 04:22
I'm facing the same issue with redshift_connector:
struct.error: unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)
And is affecting our production setup.

**Comment by nischay-merkle** [comment] 2023-07-14 04:26
@dataders  I'm currently using: redshift-connector 2.0.903. It's a python Client library (https://pypi.org/project/redshift-connector/) for redshift.

**Comment by fix-a-thing** [comment] 2023-07-21 10:00
I'm facing the same issue. And like in this [comment](https://github.com/aws/amazon-redshift-python-driver/issues/96#issuecomment-1607240268), it happens at 10 minutes.

It does not affect production, but development. We run 1.2 in production and develop in the same. Here we get the error: `SSL SYSCALL error: EOF detected`. Again it happens after 10 minutes.

As we are planning to upgrade to 1.6 soon, I just got the latest rc version using:
- Running with dbt=1.6.0-rc1
- Registered adapter: redshift=1.6.0-rc1
- dbt-redshift==1.6.0rc1

And here I'm getting: `unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)`
I guess it is some connection timeout? It used to work, but now it doesn't, not sure what changed.

**Comment by dbeatty10** [comment] 2023-07-21 16:27
> I guess it is some connection timeout?

Yep, that error message comes from a networking issue.

There's an issue open [here](https://github.com/aws/amazon-redshift-python-driver/issues/164) to improve the error message, and [here](https://github.com/aws/amazon-redshift-python-driver/issues/142#issuecomment-1601152165) are Amazon's recommendations to avoid it.

**Comment by BeltranCunef** [comment] 2023-08-02 10:15
I'm facing the same issue, in my case I'm not using redshift-connector. My dbt versions are the following:

`dbt-core 1.5.4
dbt-postgres = 1.5.4
dbt-redshift = 1.5.8`

The error commented before on the post raises commonly in a specific table, but exceptionally raises in other tables. I'm just running some sql scripts in order to deploy changes on my databases. It only happens on GitHub, same jobs run correctly at DBT Cloud.

**Comment by dnascimento** [comment] 2023-09-05 01:29
What can I do to avoid loosing database connection? Is that a parameter?

**Comment by davyto** [comment] 2023-09-05 08:35
we are also getting this error with `dbt-core 1.6.1` and `dbt-redshift 1.6.1`

**Comment by Sairam90** [comment] 2024-12-06 17:45
Getting this error when using redshift-connector ==2.1.1 and working with multiprocessing.. any ideas ?

**Comment by dbeatty10** [comment] 2024-12-06 17:55
@Sairam90 [dbt-core](https://pypi.org/project/dbt-core/) doesn't support [safe parallel execution](https://docs.getdbt.com/reference/dbt-commands#parallel-execution) for multiple invocations in the same process. See below for more details:
- https://docs.getdbt.com/reference/programmatic-invocations#parallel-execution-not-supported
- https://docs.getdbt.com/reference/dbt-commands#parallel-execution

If you are experiencing a problem with a supported feature of dbt-core / dbt-redshift, please open a new issue (and reference this one).

If you are getting an error message similar to "unpack_from requires a buffer ..." it is most likely a bug report that is appropriate to open in the [`amazon-redshift-python-driver`](https://github.com/aws/amazon-redshift-python-driver/issues) repo.
